/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'benoit' at '18/02/16 16:49' with Gradle 2.6
 *
 * @author benoit, @date 18/02/16 16:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
